### ISSUE TITLE
Impossible to login anymore

### ISSUE THREAD

**Issue by ClementCHA** [auth0-samples/auth0-uwp-oidc-samples#19]
# Issue Report

If you are reporting a bug, please fill the sections below (if they are applicable), otherwise feel free to delete those that don't apply. Thank you! 🙏🏼

### Description

Any recent breaking change  ? Impossible to login anymore since a week now. 

### Expected behaviour

Authentification success

### Actual behaviour 

When use for the first time, the authentification window is opening successfully. If we create new user or even try to connect with existent username+ password => Authentification window is closing and it's impossible to connect. The window is briefly opening then immediatly closing. Important NOTE : We still can create new account. (screenShot 1)

### Steps to reproduce the problem

1) Launch the project for the first time 
2) authentification or inscription 
3) Fill the different text field 
4) Create/Login button
5) Window is closing
6) Click again on "Create/Login" 
7) the window is opening then immediatly closing 
8) Impossible to connect or to create new user again

### Language / Framework Versions

** UWP project C# ** 

### Testing environment

1. **Windows 11 Pro**

### Screenshots

![Auth Success HIde](https://user-images.githubusercontent.com/73785703/193548955-ecdcf0da-2c70-4669-b88b-506d7781b394.png)
![Elow Playground Hide](https://user-images.githubusercontent.com/73785703/193548957-71763e2d-7c5e-4808-a495-580b54d98240.png)

**Filling this, you're helping yourself and repo maintainers in solving your issues quicker! Teamwork makes the dreamwork 🤜🏼🤛🏻**

**Comment by frederikprijck** [comment]
Please do not open the same issue twice, closing in favor of https://github.com/auth0/auth0-oidc-client-net/issues/232
